---
conda_env_name: "pybridge_env"
conda_python_version: "3.12"
miniconda_bin_dir: "/usr/local/miniconda3/bin"

# 로컬 파일 경로
local_requirements_path: "files/requirements.txt"
remote_temp_dir: "/tmp/conda_env_setup"
