---
python_version: "3.12.0"
openssl_version: "1.1.1w"

# 설치 경로 설정
python_install_dir: "/usr/local/python312"
openssl_install_dir: "/usr/local/openssl111"

# 소스 파일 이름
python_src_file: "Python-{{ python_version }}.tar.xz"
openssl_src_file: "openssl-{{ openssl_version }}.tar.gz"

# 로컬 파일 경로 (Ansible 실행 위치 기준)
local_files_path: "../files"
remote_temp_dir: "/tmp/python_install"
